name: Deploy
run-name: "${{ github.actor }} is deploying: ${{ github.event.head_commit.message }}"
on:
  push:
    branches:
      - 'master'
env:
  APP_NAME: ${{ vars.APP_NAME }}
  AWS_REGION: ${{ vars.AWS_REGION }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
  CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
  CLOUDFLARE_ACCOUNT_ID: ${{ vars.CLOUDFLARE_ACCOUNT_ID }}
  GITHUB_REPOSITORY_NAME: ${{ github.event.repository.name }}
  NODE_VERSION: ${{ vars.NODE_VERSION }}
  STRAPI_HOST: ${{ vars.STRAPI_HOST }}
  STRAPI_PORT: ${{ vars.STRAPI_PORT }}
  STRAPI_PROTOCOL: ${{ vars.STRAPI_PROTOCOL }}
  STRAPI_TOKEN: ${{ secrets.STRAPI_TOKEN }}
jobs:
  deploy-infra:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform
    steps:
      - name: "checkout"
        uses: actions/checkout@v4
      - name: "setup terraform"
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false
      - name: "authenticate with aws"
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
      - name: "cache terraform state"
        id: cache
        uses: actions/cache@v4
        with:
          key: ${{ hashFiles('terraform/**') }}
          path: |
            terraform/.terraform
            terraform/.terraform.lock.hcl
      - name: "terraform init"
        if: steps.cache.outputs.cache-hit != 'true'
        run: terraform init -backend-config="bucket=$APP_NAME-terraform" -backend-config="key=terraform-state" -backend-config="region=$AWS_REGION"
      - name: "terraform apply"
        if: steps.cache.outputs.cache-hit != 'true'
        run: terraform apply -auto-approve
  test-build:
    needs:
      - deploy-infra
    runs-on: ubuntu-latest
    container:
      image: node:18-bookworm-slim
    env:
      CLOUDFLARE_WEB_ANALYTICS_TOKEN: ${{ secrets.CLOUDFLARE_WEB_ANALYTICS_TOKEN }}
    steps:
      - name: "checkout"
        uses: actions/checkout@v4
      - name: "cache packages"
        id: cache-packages
        uses: actions/cache@v4
        with:
          key: ${{ hashFiles('package.json') }}
          path: |
            .yarn/cache
            node_modules
      - name: yarn
        if: steps.cache-packages.outputs.cache-hit != 'true'
        run: yarn
      - name: mocha test
        run: "npx mocha"
      - name: "cache 11ty src"
        id: cache-11ty-src
        uses: actions/cache@v4
        with:
          key: ${{ hashFiles('src/') }}
          path: |
            _site/**
      - name: "11ty build"
        if: steps.cache-11ty-src.outputs.cache-hit != 'true'
        run: "npx @11ty/eleventy"
      - name: "upload artifact"
        uses: actions/upload-artifact@v4
        with:
          name: "11ty-output"
          path: "_site/"
  deploy:
    needs:
      - test-build
    runs-on: ubuntu-latest
    steps:
      - name: "checkout"
        uses: actions/checkout@v4
      - name: "download artifact"
        uses: actions/download-artifact@v4
        with:
          name: "11ty-output"
          path: "_site/"
      - name: Publish to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ vars.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy _site --project-name=${{ vars.APP_NAME }} --commit-dirty=true
